apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deafult-allow-exgress
  namespace: k2
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: consumer
    ports:
      - protocol: TCP
        port: 80
