apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  containers:
  - image: nginx:1.25.1
    name: app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  initContainers:
  - initContainers:
    name: init
    image: busybox:1.36.1
    command:
    - wget
    - -O-
    - google.com
status: {}
