apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - while :; do sleep 1000; done
    image: alpine:3.12.0
    name: container1
    volumeMounts:
    - mountPath: "/etc/a"
      name: temp
    resources: {}
  - command:
    - /bin/sh
    - -c
    - while :; do sleep 1000; done
    image: alpine:3.12.0
    name: container2
    volumeMounts:
    - mountPath: "/etc/b"
      name: temp
    resources: {}
  volumes:
    - name: temp
      emptyDir:
        sizeLimit: 500Mi
status: {}
