apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: logs-pvc-pod
spec:
  volumes:
    - name: logs-pvc-storage
      persistentVolumeClaim:
        claimName: logs-pvc
  containers:
    - name: logs-pvc-container
      image: nginx
      volumeMounts:
        - mountPath: "/var/log/nginx"
          name: logs-pvc-storage
