apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    version: v2
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        version: v2
    spec:
      containers:
      - image: nginx:1.23.4
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: '/usr/share/nginx/html'
      initContainers:
      - image: busybox
        name: busybox
        command: ['/bin/sh', '-c', 'echo "New deployment" > /work-dir/index.html']
        volumeMounts:
        - name: workdir
          mountPath: '/work-dir'
      volumes:
      - name: workdir
        emptyDir: {}

