apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cj-busybox
spec:
  jobTemplate:
    activeDeadlineSeconds: 12
    metadata:
      creationTimestamp: null
      name: cj-busybox
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: cj-busybox
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
