apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello-world
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: /var/log
      name: dir-volume
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
        ephemeral-storage: "1Gi"
      limits:
        memory: "500Mi"
        ephemeral-storage: "2Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: dir-volume
    emptyDir: {}
status: {}
