apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
  namespace: rq-demo
spec:
  containers:
  - image: nginx
    name: hello-world
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "500Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
