apiVersion: v1
kind: Namespace
metadata:
  name: rq-demo
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app
  namespace: rq-demo 
spec:
  hard:
    pods: "2"
    requests.cpu: "2"
    requests.memory: 500Mi
