apiVersion: v1
kind: Pod
metadata:
  labels:
    run: loop
  name: loop
spec:
  containers:
  - image: busybox
    name: loop
    command: ['sh', '-c', 'for i in 1 2 3 4 5 6 7 8 9 10; do echo "Welcome $i times"; done;' ]
    resources: {}
  restartPolicy: Never