apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod
spec:
  containers:
  - image: alpine
    name: first
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 60; done;"]
    volumeMounts:
    - mountPath: /etc/a
      name: logs-volume
  - image: alpine
    name: second
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 60; done;"]
    volumeMounts:
    - mountPath: /etc/b
      name: logs-volume
  volumes:
  - name: logs-volume
    emptyDir: {}
