apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: web-server
spec:
  containers:
  - image: nginx:1.23.0
    name: pod
    ports:
    - containerPort: 80
    resources: {}
    startupProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 30
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
