apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-blue
  name: nginx-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-blue
        version: blue
    spec:
      containers:
      - image: nginx:1.23.0
        name: nginx
        resources: {}
status: {}
