apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-green
  name: nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-green
        version: green
    spec:
      containers:
      - image: nginx:1.23.4
        name: nginx
        resources: {}
status: {}
