apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox-2
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    volumeMounts:
    - mountPath: "/etc/foo"
      name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: mypvc

