apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox-1
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: vlm
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox-2
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: vlm
  volumes:
  - name: vlm
    emptyDir: {}
status: {}
