apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-security-context
  name: busybox-security-context
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox:1.36.1
    name: busybox-security-context
    volumeMounts:
    - mountPath: /data/test
      name: vlm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: vlm
    emptyDir: {}
