apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: API_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: ext-service-configmap
          key: api_endpoint
    - name: USERNAME
      valueFrom:
        configMapKeyRef:
          name: ext-service-configmap
          key: username
