apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  containers:
  - image: alpine
    name: secured-container
    securityContext:
      capabilities:
        add: [CAP_SYS_TIME]
