apiVersion: v1
kind: Pod
metadata:
  name: loop
spec:
  containers:
  - args: ["/bin/sh", "-c", "for i in 1 2 3 4 5 6 7 8 9 10; do echo \"Welcome $i times\"; done"]
    image: busybox:1.36.1
    name: loop
    resources: {}
  restartPolicy: Never
status: {}
