apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  containers:
    - name: nginx3
      image: nginx:latest
      volumeMounts:
      - name: lala
        mountPath: "/etc/lala"
        readOnly: true
  volumes:
  - name: lala
    configMap:
      name: cmvolume