apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      command: ["/bin/sh", "-c", "printenv"]
      image: nginx:latest
      env:
      - name: option
        valueFrom:
          configMapKeyRef:
            name: options
            key: var5