apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
    - name: nginx2
      command: ["/bin/sh", "-c", "printenv"]
      image: nginx:latest
      envFrom:
        - configMapRef:
            name: anotherone