apiVersion: v1
kind: Namespace
metadata:
  name: one
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-rq
  namespace: one
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
