apiVersion: v1
kind: Pod
metadata:
  labels:
    run: accepted
  name: accepted
  namespace: one
spec:
  containers:
  - image: nginx
    name: accepted
    resources:
      requests:
        cpu: 0.5
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
