apiVersion: v1
kind: Pod
metadata:
  name: data-exchange
spec:
  containers:
    - name: main-app
      image: busybox
      args:
        - /bin/sh
        - -c
        - counter=1; while :; do touch "/var/app/data/${counter}-data.txt"; counter=$((counter+1)); sleep 3; echo $counter; done;
      volumeMounts:
        - name: config-volume
          mountPath: /var/app/data/
    - name: sidecar
      image: busybox
      args:
        - /bin/sh
        - -c
        - while :; do echo $(ls -la /var/app/data/ | grep data | wc -l); sleep 10; done;
      volumeMounts:
      - name: config-volume
        mountPath: /var/app/data/
  volumes:
    - name: config-volume
      emptyDir: {}
