apiVersion: v1
kind: Pod
metadata:
  name: complex-pod
spec:
  initContainers:
  - image: busybox
    name: setup
    args:
      - /bin/sh
      - -c
      - wget -O- google.com
  containers:
  - image: nginx
    name: app
    ports:
    - containerPort: 80
  