apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-test
spec:
  podSelector:
    matchLabels:
      app: nettest
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: granted
